# Generated by Django 5.0.7 on 2024-07-24 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('recurring_rate', models.PositiveIntegerField(default=1)),
                ('last_done', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
